name: roboshop 
services:
  mongodb:
    build: ./mongodb
    image: ec2-user/mongodb:v1   
    container_name: mongodb        
  catalogue:
    build: ./catalogue
    image: ec2-user/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  frontend:
    build: ./frontend
    image: ec2-user/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
  user:
    build: ./user
    image: ec2-user/user:v1
    container_name: user
    environment:
      MONGO: true
      REDIS_URL: 'redis://redis:6379'
      MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on:
    - redis
    - mongodb
  redis:
    image: redis:7
    container_name: redis # docker run -d --name redis --network roboshop redis:7

    cart:
    build: ./cart
    image: ec2-user/cart:v1
    container_name: cart
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      CATALOGUE_PORT: 8080
    depends_on:
    - redis
    - catalogue
  
networks:
  default: 
    name: roboshop
    driver: bridge
    external: false

